#!/usr/bin/env python3
"""Emit docs/QUESTION-CARD-MAP.md: performance question -> backing flashcards.

Uses the precise `supports_question` link authored on each card (a card backs a
question when the question id appears in that card's supports_question). Lets
you verify, for every question in data/questions.json (dev AND held_out), which
flashcards teach it, plus a per-topic coverage table. CARS is performance-only,
so CARS questions intentionally have no backing cards.

Exit code is non-zero if any non-CARS question has no backing card.

Run:  python scripts/build_question_card_map.py   (after building bank + cards)
"""

from __future__ import annotations

import csv
import re
import sys
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def snippet(text: str, n: int = 95) -> str:
    """One-line preview: drop cloze markup / passage prefix, collapse spaces."""
    text = re.sub(r"\{\{c\d+::(.*?)\}\}", r"[\1]", text)
    text = text.replace("PASSAGE", "").replace("QUESTION", "")
    text = " ".join(text.split())
    return text if len(text) <= n else text[: n - 1] + "…"


def load_cards() -> list[dict]:
    rows = list(csv.DictReader((DATA / "flashcards-dev.csv").open(encoding="utf-8")))
    cards = []
    for r in rows:
        tag = r.get("tags", "")
        topic = tag.split("topic:", 1)[1].split()[0] if "topic:" in tag else ""
        sq = (r.get("supports_question") or "").strip()
        supports = [x.strip() for x in sq.split("|") if x.strip()]
        cards.append({
            "topic": topic,
            "type": r["note_type"],
            "front": r["text"],
            "supports": supports,
        })
    return cards


def main() -> int:
    questions = json.loads((DATA / "questions.json").read_text(encoding="utf-8"))
    cards = load_cards()

    # question id -> backing cards (via supports_question)
    backing: dict[str, list[dict]] = {}
    for c in cards:
        for qid in c["supports"]:
            backing.setdefault(qid, []).append(c)

    qs_by_topic: dict[str, list[dict]] = {}
    for q in questions:
        qs_by_topic.setdefault(q["topic_id"], []).append(q)

    lines: list[str] = []
    lines.append("# Question ↔ flashcard map")
    lines.append("")
    lines.append("_Generated by `scripts/build_question_card_map.py` — do not "
                 "edit by hand._")
    lines.append("")
    lines.append("A flashcard **backs** a performance question when the "
                 "question id is listed in that card's `supports_question`. "
                 "CARS is performance-only, so CARS questions have no backing "
                 "cards by design.")
    lines.append("")

    # coverage table
    lines.append("## Coverage by topic")
    lines.append("")
    lines.append("| Topic | Questions (dev/held_out) | Questions with >=1 card | Backing cards |")
    lines.append("|-------|--------------------------|-------------------------|---------------|")
    uncovered: list[str] = []
    for topic in sorted(qs_by_topic):
        qlist = qs_by_topic[topic]
        dev = sum(1 for q in qlist if q["split"] == "dev")
        held = sum(1 for q in qlist if q["split"] == "held_out")
        is_cars = topic.startswith("cars_")
        with_card = sum(1 for q in qlist if backing.get(q["id"]))
        ncards = sum(1 for c in cards if c["topic"] == topic)
        if not is_cars:
            uncovered += [q["id"] for q in qlist if not backing.get(q["id"])]
        covered_cell = "— (CARS)" if is_cars else f"{with_card}/{len(qlist)}"
        lines.append(f"| `{topic}` | {dev}/{held} | {covered_cell} | {ncards} |")
    lines.append("")

    # per-topic detail: each question with its backing cards
    lines.append("## Detail — each question and the cards that teach it")
    lines.append("")
    for topic in sorted(qs_by_topic):
        lines.append(f"### `{topic}`")
        lines.append("")
        for q in qs_by_topic[topic]:
            lines.append(f"- `{q['id']}` ({q['split']}) — {snippet(q['stem'])}")
            cs = backing.get(q["id"], [])
            if cs:
                for c in cs:
                    lines.append(f"    - ↳ ({c['type']}) {snippet(c['front'])}")
            elif topic.startswith("cars_"):
                lines.append("    - ↳ _(CARS: no flashcard by design)_")
            else:
                lines.append("    - ↳ ⚠️ **no backing card**")
        lines.append("")

    (DOCS / "QUESTION-CARD-MAP.md").write_text("\n".join(lines) + "\n",
                                               encoding="utf-8")

    science = sum(1 for q in questions if q["section"] != "CARS")
    covered = science - len(uncovered)
    print("wrote docs/QUESTION-CARD-MAP.md")
    print(f"  {len(questions)} questions, {len(cards)} cards")
    print(f"  science questions with >=1 backing card: {covered}/{science}")
    if uncovered:
        print(f"  UNCOVERED science questions: {sorted(uncovered)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
